language: node_js
node_js:
  - "8"
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

branches:
  only:
  - master

install:
  - npm install

script:
  # - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI // FIXME
  - ng build --prod --base-href /7daystodie/SevenDaysToDie/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  project-name: 7daystodie
  local-dir: dist
  on:
    branch: master
